name: ACL Update
on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '* */1 * * *'

env:
  TZ: Asia/Taipei

jobs:
  update_rules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: HoshinoNeko/China-ISP
        ref: main

    - name: Update Rules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_REPO: HoshinoNeko/China-ISP
        DEPLOY_BRANCH: main
        COMMIT_USER: "GITHUB ACTIONS[Bot]"
        COMMIT_EMAIL: 21078047+HoshinoNeko@users.noreply.github.com
      run: |
        ./process.sh || true
        cat /home/runner/work/_temp/104bf1f8-ed64-4f7a-b8c0-550313d1485a.sh
        git add .
        git config user.name ${COMMIT_USER}
        git config user.email ${COMMIT_EMAIL}
        git commit -m "Updated by Actions at `date +'%Y-%m-%d %H:%M:%S'`" && git push
        #git push -u origin ${DEPLOY_BRANCH}
        #git push
        return 0
